# This rule is not used by the project cluster-inspector-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over aiops.zperkins.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-inspector-operator
    app.kubernetes.io/managed-by: kustomize
  name: inspectionreport-admin-role
rules:
- apiGroups:
  - aiops.zperkins.dev
  resources:
  - inspectionreports
  verbs:
  - '*'
- apiGroups:
  - aiops.zperkins.dev
  resources:
  - inspectionreports/status
  verbs:
  - get
